# Generated by Django 3.2.3 on 2025-02-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20250202_1738'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_shoppingcart',
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='shoppinglist_unique'),
        ),
    ]
